### ISSUE TITLE
Home Page button not working.

### ISSUE THREAD

**Issue by Gaurabchettri7653** [Gaurabchettri7653/HRMS-#2]
The button of the home page is not working/clicking. Please fix that Asap.

**Comment by ElecTrifY69** [comment]
I'm experiencing some issues with that. I'll consult with my peer and let you know once it's resolved.

**Comment by Gaurabchettri7653** [comment]
> I'm experiencing some issues with that. I'll consult with my peer and let you know once it's resolved.

Thanks for the update! Let me know if there's anything I can assist with in the meantime. I'll wait for your confirmation once the issue is resolved.
